# https://cloud.google.com/config-connector/docs/reference/resource-docs/cloudbuild/cloudbuildtrigger
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: cloudbuildtrigger-github
  namespace: config-control
spec:
  # Cloud Build Triggers for GitHub repositories require that you first connect
  # your GCP project to your GitHub repository. More info:
  # https://cloud.google.com/cloud-build/docs/automating-builds/create-github-app-triggers
  description: Trigger for main branch of the GitHub repo https://github.com/OperationalFallacy/gcp-cloudbuild-demo
  disabled: false
  location: us-central1
  github:
    owner: OperationalFallacy
    name: gcp-cloudbuild-demo
    push:
      branch: ^main$
  ignoredFiles:
    - "**/*.md"
  includedFiles:
    - "src/**"
    - "*.yaml"
  includeBuildLogs: INCLUDE_BUILD_LOGS_UNSPECIFIED
  substitutions:
    "_SERVICE_NAME": "service-name"
  filename: "src/cloudbuild.yaml"
  serviceAccountRef:
    name: cbt-demo-srvacct
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: cbt-demo-srvacct
  namespace: config-control
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: cbt-srvacct-role-logger
  namespace: config-control
spec:
  memberFrom:
    serviceAccountRef:
      name: cbt-demo-srvacct
  resourceRef:
    kind: Project
    external: projects/skylab-contino
  role: roles/logging.logWriter
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: cbt-srvacct-role-functions
  namespace: config-control
spec:
  memberFrom:
    serviceAccountRef:
      name: cbt-demo-srvacct
  resourceRef:
    kind: Project
    external: projects/skylab-contino
  role: roles/cloudfunctions.developer
