steps:

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args: ["echo", "Building function..."]
    id: BUILD

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args: ["echo", "Testing function..."]
    id: TEST

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - $_FUNCTION_NAME
      - --region=$_FUNCTION_REGION
      - --source=src/
      - --trigger-http
      - --runtime=$_FUNCTION_RUNTIME
      - --project=$_FUNCTION_PROJECT
      - --entry-point=$_ENTRY_POINT
    id: DEPLOY

substitutions:
  _FUNCTION_PROJECT: skylab-contino
  _FUNCTION_NAME: nodejs-demo
  _FUNCTION_REGION: us-central1
  _FUNCTION_RUNTIME: nodejs18
  _ENTRY_POINT: handler

options:
  logging: CLOUD_LOGGING_ONLY